name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  # Run tests
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Test
      env:
        SPEECHIFY_API: ${{ secrets.SPEECHIFY_API }}
      run: |
        python hello-world.py --key "$SPEECHIFY_API"
